kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: iscsi-block-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
  resources:
    requests:
      storage: 1Gi
  storageClassName: storage-class-iscsi
